
#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'HDLAuthID_Example' do
  pod 'HDLAuthID'
  pod 'AFNetworking'
#  pod 'HDLAuthID',:path => '../'
#  pod 'HDLAuthID',:podspec => '../HDLAuthID.podspec'
end
